# Generated by Django 5.0.3 on 2025-03-04 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='nfctag',
            name='aanwezig',
            field=models.BooleanField(default=False),
        ),
    ]
